# mod dependency list optional
dependency:
  afloesch/megamod/.skse.mm.yml: ">=v2.0.20"
# optional extract directory for mod archive relative to 
# the specified game install folder. (Unix paths)
directory: /
# optional game metadata
game:
  # optional, but best practice to include the game executable name
  executable: SkyrimSE.exe
  # gameVersion optional, defaults to all versions. Used to enforce game version compatibility between mods
  version: ">=v1.5.97"
# name is optional will default to the repo name
name: Address Library Plugin for SKSE
# mod ESRB rating. if none specified then mod is safe for all ages.
rating:
  esrb: E # one of E, eC, E10+, T, M, AO
# url optional for mod releases. defaults to releases archive
url: https://github.com/afloesch/megamod/releases/download/v0.1.0/All.in.one-32444-2-1582543914.zip
# version/tag required
version: v0.1.0