# description is optional
description: optional short description text goes here.
# mod dependency list optional
dependency:
  afloesch/megamod/main/.addresslibrary.mm.yml: ">=v0.1.0"
  afloesch/megamod/main/.skse.mm.yml: ">=v2.0.20"
# optional extract directory for mod archive relative to 
# the specified game install folder. (Unix paths)
directory: /
# optional game metadata
game:
  # optional, but best practice to include the game executable name
  executable: SkyrimSE.exe
  # gameVersion optional, defaults to all versions. Used to enforce game version compatibility between mods
  version: ">=v1.5.97"
# name is optional will default to the repo name
name: ConsoleUtilSSE
# mod ESRB rating. if none specified then mod is safe for all ages.
rating:
  esrb: E # one of E, eC, E10+, T, M, AO
# url optional for mod releases. defaults to releases archive
url: https://github.com/Ryan-rsm-McKenzie/ConsoleUtilSSE/releases/download/1.3.2/ConsoleUtilSSE.zip
# version/tag required
version: v1.3.2